import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import copy from "esbuild-plugin-copy";
const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;



const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"moment",
		...builtins],
	format: "cjs",
	target: "esnext",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "test_vault/.obsidian/plugins/obsidian-inputs/main.js",
	plugins:[
		copy({
			resolveFrom: "cwd",
			assets: [
				{ from: "src/styles.css", to: `test_vault/.obsidian/plugins/obsidian-inputs/styles.css` },
				{ from: "src/manifest.json", to: `test_vault/.obsidian/plugins/obsidian-inputs/manifest.json` },
				{ from: "data.json", to: `test_vault/.obsidian/plugins/obsidian-inputs/data.json` }
			],
			watch: false
		})
	]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
