name:  Build Obsidian Plugin

on: workflow_dispatch

env:
    PLUGIN_NAME: obsidian-inputs
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"

            - name: Get Package Version
              id: get_package_version
              run: echo "PACKAGE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

            - name: Build
              id: build
              run: |
                  echo Building for version PACKAGE_VERSION
                  npm install
                  npm run build
                  zip -jr ${{ env.PLUGIN_NAME }}-${{ env.PACKAGE_VERSION }}.zip test_vault/.obsidian/plugins/obsidian-inputs/*
                  ls
                  echo Dist folder:
                  ls dist

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ env.PACKAGE_VERSION }}
                files: |
                    ${{ env.PLUGIN_NAME }}-${{ env.PACKAGE_VERSION }}.zip
                    main.js
                    manifest.json
                    styles.css
                    data.json
