name: Release Obsidian plugin

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'

            - name: Build plugin
              run: |
                  npm install -g yarn
                  yarn install
                  yarn build

            - name: Create release
              uses: actions/create-release@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
                  body_file: release-notes.md
                  draft: true  # Set to true if you want to create a draft release
                  prerelease: true  # Set to true if it's a pre-release
                  file_glob: 'main.js manifest.json styles.css' # '**/*.{js,css,json}'  # Include all relevant files in the release

